In [19]:
import tifffile
import numpy as np 
import matplotlib.pyplot as plt
# Ouvrir l'image TIFF
image = tifffile.imread('Examples/NMC.tif')
im0=image[:,:,0]
shape0=im0.shape
# Obtenir la forme de l'image
shape = image.shape
print(f"La forme de l'image est : {shape0}")
print(f"les valeurs unique de ça c'est : {np.unique(im0)}")
print("==================\n",image)


La forme de l'image est : (252, 252)
les valeurs unique de ça c'est : [  0 128 255]
 [[[255 255   0 ... 255 255 255]
  [255   0   0 ... 255 255 128]
  [255   0   0 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[255 255 255 ... 255 255 255]
  [  0 255 255 ... 128 128 128]
  [255   0   0 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[  0   0 255 ... 128 128 128]
  [  0   0   0 ... 128 128 128]
  [255 255   0 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 ...

 [[  0   0   0 ... 255   0   0]
  [255   0   0 ...   0 128 128]
  [255   0   0 ... 255 128 128]
  ...
  [128 128 128 ...   0 255   0]
  [128 128 128 ... 255 255 255]
  [128 128 255 ... 255 255 255]]

 [[  0   0   0 ...   0 128 128]
  [  0   0   0 ...   0 128 128]
  [  0   0   0 ... 128 128 128]
  ...
  [128 